service:
  name: website-scraping
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1
  profile: serverless-admin
  stackTags:
    PROJECT: WEBSITE_SCRAPING

functions:
  scrape:
    handler: handler.scrape
    events:
      - http:
          method: get
          path: ''

